# Generated by Django 3.1.7 on 2021-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], max_length=30),
        ),
    ]
