# Generated by Django 3.1.7 on 2021-02-27 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('mob_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
